# Import Dependencies

In [1]:
import pandas as pd
from sqlalchemy import create_engine

# Load CSV Data

In [16]:
netflix_file = "Resources/netflix_titles.csv"
netflix_df = pd.read_csv(netflix_file)        
netflix_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [17]:
wiki_file = "Resources/wiki_movie_plots_deduped.csv"
wiki_df = pd.read_csv(wiki_file)
wiki_df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr..."
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov..."
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed..."
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...

# Transform Netflix_file

In [18]:
# Filter Only Movies type.
netflix_df = netflix_df[~netflix_df['type'].str.contains("TV Show")]

In [24]:

# Create a filtered dataframe from specific columns
netflix_cols = ["title", "country", "release_year", "listed_in"]
netflix_transformed= netflix_df[netflix_cols].copy()

# Rename the column headers
netflix_transformed = netflix_transformed.rename(columns={"title": "title",
                                                          "country": "country",
                                                          "release_year": "release_year",
                                                            "listed_in" : "genre"})
#netflix_transformed.head()

In [25]:
# Filter only rows for "release_year" 2010 to 2017.

netflix_filtered = netflix_transformed[(netflix_transformed["release_year"] >= 2010) & (netflix_transformed["release_year"] < 2018)]
netflix_filtered

,title,country,release_year,genre
1,7:19,Mexico,2016,"Dramas, International Movies"
2,23:59,Singapore,2011,"Horror Movies, International Movies"
10,1922,United States,2017,"Dramas, Thrillers"
15,Oct-01,Nigeria,2014,"Dramas, International Movies, Thrillers"
19,'89,United Kingdom,2017,Sports Movies
...,...,...,...,...
7770,Zinzana,"United Arab Emirates, Jordan",2015,"Dramas, International Movies, Thrillers"
7772,Zipi & Zape y la Isla del Capitan,Spain,2016,"Children & Family Movies, Comedies"
7773,Zoé: Panoramas,Mexico,2016,"Documentaries, International Movies, Music & M..."
7776,Zokkomon,India,2011,"Children & Family Movies, Dramas"
7783,Zubaan,India,2015,"Dramas, International Movies, Music & Musicals"

# Transform Wiki_file

In [41]:
# Checked for missing Plot entries
wiki_df.dropna(subset=['Plot'], how='all', inplace=True)
#wiki_df


# Create a filtered dataframe from specific columns
wiki_cols = ["Title", "Release Year", "Director", "Genre", "Plot"]
wiki_transformed= wiki_df[wiki_cols].copy() 

# Rename the column headers
wiki_transformed = wiki_transformed.rename(columns={"Title": "title",
                                                    "Release Year" : "release_year",
                                                          "Director": "director",
                                                            "Genre" : "genre",
                                                           "Plot": "plot"})
                                           
#wiki_transformed.head()

In [40]:
# Filter only rows for "release_year" 2010 to 2017.

wiki_filtered = wiki_transformed[(wiki_transformed["release_year"] >= 2010) & (wiki_transformed["release_year"] < 2018)]
#wiki_filtered

wiki_dropdup = wiki_filtered.drop_duplicates(subset=['title'], keep=False)

#wiki_dropdup